// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: 'modules/module-1-ros2',
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference/ros2-concepts',
        },
      ],
    },
    {
      type: 'category',
      label: 'Community',
      items: [
        'community/contribution-guide',
      ],
    },
  ],
};

export default sidebars;